spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/CRUD
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create